// Script to seed the database with sample movies and admin user
// Run with: node scripts/seed.js

const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/mindmirror';

const UserSchema = new mongoose.Schema({
  email: String,
  password: String,
  name: String,
  role: String,
  favorites: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Movie' }],
  watchlist: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Movie' }],
  createdAt: { type: Date, default: Date.now },
});

const MovieSchema = new mongoose.Schema({
  title: String,
  description: String,
  type: String,
  imdbId: String,
  tmdbId: String,
  year: Number,
  duration: String,
  seasons: Number,
  episodes: Number,
  genre: [String],
  category: [String],
  thumbnail: String,
  backdrop: String,
  trailer: String,
  rating: Number,
  views: { type: Number, default: 0 },
  featured: Boolean,
  createdAt: { type: Date, default: Date.now },
});

const User = mongoose.models.User || mongoose.model('User', UserSchema);
const Movie = mongoose.models.Movie || mongoose.model('Movie', MovieSchema);

const sampleMovies = [
  {
    title: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    type: 'movie',
    imdbId: 'tt1375666',
    tmdbId: '27205',
    year: 2010,
    duration: '2h 28m',
    genre: ['Action', 'Sci-Fi', 'Thriller'],
    category: ['trending', 'action'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    rating: 8.8,
    featured: true,
  },
  {
    title: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    type: 'movie',
    imdbId: 'tt0468569',
    tmdbId: '155',
    year: 2008,
    duration: '2h 32m',
    genre: ['Action', 'Crime', 'Drama'],
    category: ['trending', 'action'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hkBaDkMWbLaf8B1lsWsKX7Ew3Xq.jpg',
    rating: 9.0,
    featured: true,
  },
  {
    title: 'Interstellar',
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    type: 'movie',
    imdbId: 'tt0816692',
    tmdbId: '157336',
    year: 2014,
    duration: '2h 49m',
    genre: ['Adventure', 'Drama', 'Sci-Fi'],
    category: ['trending', 'drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/pbrkL804c8yAv3zBZR4QPEafpAR.jpg',
    rating: 8.6,
    featured: true,
  },
  {
    title: 'Breaking Bad',
    description: 'A high school chemistry teacher turned methamphetamine producer partners with a former student to secure his family\'s future.',
    type: 'series',
    imdbId: 'tt0903747',
    tmdbId: '1396',
    year: 2008,
    seasons: 5,
    episodes: 62,
    genre: ['Crime', 'Drama', 'Thriller'],
    category: ['trending', 'drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    rating: 9.5,
    featured: true,
  },
  {
    title: 'Stranger Things',
    description: 'When a young boy disappears, his mother, a police chief and his friends must confront terrifying supernatural forces in order to get him back.',
    type: 'series',
    imdbId: 'tt4574334',
    tmdbId: '66732',
    year: 2016,
    seasons: 4,
    episodes: 42,
    genre: ['Drama', 'Fantasy', 'Horror'],
    category: ['trending', 'horror'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    rating: 8.7,
    featured: true,
  },
  {
    title: 'The Shawshank Redemption',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    type: 'movie',
    imdbId: 'tt0111161',
    tmdbId: '278',
    year: 1994,
    duration: '2h 22m',
    genre: ['Drama'],
    category: ['drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    rating: 9.3,
    featured: false,
  },
  {
    title: 'The Office',
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    type: 'series',
    imdbId: 'tt0386676',
    tmdbId: '2316',
    year: 2005,
    seasons: 9,
    episodes: 201,
    genre: ['Comedy'],
    category: ['comedy'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/7DJKHzAi83BmQrWLrYYOqcoKfhR.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/3K8gfuNfF8nYSz5t9PkYL9x3PaB.jpg',
    rating: 9.0,
    featured: false,
  },
  {
    title: 'The Conjuring',
    description: 'Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.',
    type: 'movie',
    imdbId: 'tt1457767',
    tmdbId: '138843',
    year: 2013,
    duration: '1h 52m',
    genre: ['Horror', 'Mystery', 'Thriller'],
    category: ['horror'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/wVYREutTvI2tmxr6ujrHT704wGF.jpg',
    featured: false,
  },
  {
    title: 'Game of Thrones',
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy re-emerges in the far north.',
    type: 'series',
    imdbId: 'tt0944947',
    tmdbId: '1399',
    year: 2011,
    seasons: 8,
    episodes: 73,
    genre: ['Action', 'Adventure', 'Drama'],
    category: ['trending', 'drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/u3bVAo64vpIGEL6oBZOLc3KPZFU.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gDVrVowBu0X8cR7Tgcc8Lzu9RVw.jpg',
    rating: 9.2,
    featured: false,
  },
  {
    title: 'The Crown',
    description: 'Follows the political rivalries and romance of Queen Elizabeth II, Princess Diana, and Prime Minister Margaret Thatcher in the second half of the twentieth century.',
    type: 'series',
    imdbId: 'tt4786824',
    tmdbId: '60573',
    year: 2016,
    seasons: 5,
    episodes: 50,
    genre: ['Biography', 'Drama', 'History'],
    category: ['drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/mjiUx10fK7yVu8sB0gNEQ1RR8jv.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/l0qVQb3eCd7Hh1XNpPwZxKHR0H3.jpg',
    rating: 8.6,
    featured: false,
  },
  {
    title: 'The Mandalorian',
    description: 'The travels of a lone bounty hunter in the Star Wars universe after the fall of the Empire.',
    type: 'series',
    imdbId: 'tt8111088',
    tmdbId: '82856',
    year: 2019,
    seasons: 3,
    episodes: 24,
    genre: ['Action', 'Adventure', 'Drama'],
    category: ['trending', 'action'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/7VeHhKIu5o5pq0g1ZHc1zSY9wk.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/WCM3T4S4iJy8y5gFcMFfBLwLbQ.jpg',
    rating: 8.7,
    featured: false,
  },
  {
    title: 'Westworld',
    description: 'At the intersection of the near future and the reimagined past, waits a world in which every human appetite can be indulged without consequences.',
    type: 'series',
    imdbId: 'tt5574490',
    tmdbId: '63639',
    year: 2016,
    seasons: 4,
    episodes: 36,
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    category: ['trending', 'drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/hJdcYkF9LoE3n8mYBQBdESRXU3.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gbEhIlHvn4G5qpJAI5jQsT99Dqm.jpg',
    rating: 8.5,
    featured: false,
  },
  {
    title: 'Chernobyl',
    description: 'The true history of one of the worst man-made catastrophes in history, the chernobyl nuclear accident.',
    type: 'series',
    imdbId: 'tt7366338',
    tmdbId: '65139',
    year: 2019,
    seasons: 1,
    episodes: 5,
    genre: ['Drama', 'History', 'Thriller'],
    category: ['drama', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/7bWxiMwMDD6VY12fSh5L1vSmNqX.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/kyR5dm0pnrVzKbPk0RkZP1JLVwS.jpg',
    rating: 9.3,
    featured: false,
  },
  {
    title: 'True Detective',
    description: 'An American anthology police detective series that depicts different characters dealing with mysteries in different towns.',
    type: 'series',
    imdbId: 'tt2356777',
    tmdbId: '60573',
    year: 2014,
    seasons: 4,
    episodes: 24,
    genre: ['Crime', 'Drama', 'Mystery'],
    category: ['drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/1I8OXqL3CWAxb9PwkpC8JpUGLVT.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/lyRpifWQd7C32hPdTxJ0Pct0i8i.jpg',
    rating: 8.9,
    featured: false,
  },
  {
    title: 'Succession',
    description: 'The Roy family, known for controlling the biggest media and entertainment company in the world, deals with family politics and truncated marriages.',
    type: 'series',
    imdbId: 'tt7660850',
    tmdbId: '69051',
    year: 2018,
    seasons: 4,
    episodes: 39,
    genre: ['Drama'],
    category: ['drama', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/eUDV2jNqPKjSvwGJD7c0J2psMIl.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/6f5YYpwUhgA2MKc5Hfq8vyxJFDT.jpg',
    rating: 9.0,
    featured: false,
  },
  {
    title: 'The Last of Us',
    description: 'Joel, a smuggler tasked with a seemingly simple job, must escort Ellie, a young girl immune to a fungal infection that has ravaged humanity, across a dangerous world.',
    type: 'series',
    imdbId: 'tt6468322',
    tmdbId: '100402',
    year: 2023,
    seasons: 1,
    episodes: 9,
    genre: ['Action', 'Adventure', 'Drama'],
    category: ['trending', 'drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/uKvVjHNWjHm7f3z3W7DsWLo394w.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/ceVJzhc3yYVmYfkV9vQH2NP7NaS.jpg',
    rating: 8.8,
    featured: false,
  },
  // Additional Movies
  {
    title: 'The Shawshank Redemption',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    type: 'movie',
    imdbId: 'tt0111161',
    tmdbId: '278',
    year: 1994,
    duration: '2h 22m',
    genre: ['Drama'],
    category: ['drama', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmJy0flUdHd3CIqP.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/A62HjdWYd82MQc59I7ddhzS14qo.jpg',
    rating: 9.3,
    featured: true,
  },
  {
    title: 'Pulp Fiction',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.',
    type: 'movie',
    imdbId: 'tt0110912',
    tmdbId: '680',
    year: 1994,
    duration: '2h 34m',
    genre: ['Crime', 'Drama'],
    category: ['drama', 'action'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/d5iIlW_JByUeYw9w74lErG9hARu.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/7b6mHBkAMX5w0kP1QQzF9NKnPZn.jpg',
    rating: 8.9,
    featured: true,
  },
  {
    title: 'Forrest Gump',
    description: 'The presidencies of Kennedy and Johnson unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    type: 'movie',
    imdbId: 'tt0109830',
    tmdbId: '13',
    year: 1994,
    duration: '2h 22m',
    genre: ['Drama', 'Romance'],
    category: ['drama', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/clnuveL4b2ompBGau4l3CirFDAJ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/rU9ulKHp8g6jCPrIH01SFMvqLQL.jpg',
    rating: 8.8,
    featured: true,
  },
  {
    title: 'The Matrix',
    description: 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
    type: 'movie',
    imdbId: 'tt0133093',
    tmdbId: '603',
    year: 1999,
    duration: '2h 16m',
    genre: ['Action', 'Sci-Fi'],
    category: ['action', 'sci-fi', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/viqTkStlsSQsARA3jRvrVQ8OVko.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/n6bUvigpRFqLou6meyLPDSioGcA.jpg',
    rating: 8.7,
    featured: true,
  },
  {
    title: 'Fight Club',
    description: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into much more.',
    type: 'movie',
    imdbId: 'tt0137523',
    tmdbId: '550',
    year: 1999,
    duration: '2h 19m',
    genre: ['Drama'],
    category: ['drama', 'thriller'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/fqv4g23aw8UxIGqJChUaSz92Roo.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/rFtsE7iZVlcqPlANHrVJurHHd0w.jpg',
    rating: 8.8,
    featured: true,
  },
  {
    title: 'Gladiator',
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    type: 'movie',
    imdbId: 'tt0172495',
    tmdbId: '562',
    year: 2000,
    duration: '2h 35m',
    genre: ['Action', 'Adventure', 'Drama'],
    category: ['action', 'drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/P2HkF6XzfZdKBk71vLZWnIAl4z5.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8VzKICrRe5B_9Z5PVLVAkxq8w7Y.jpg',
    rating: 8.5,
    featured: false,
  },
  {
    title: 'The Silence of the Lambs',
    description: 'A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to catch another serial killer.',
    type: 'movie',
    imdbId: 'tt0102926',
    tmdbId: '274',
    year: 1991,
    duration: '1h 58m',
    genre: ['Crime', 'Drama', 'Thriller'],
    category: ['thriller', 'crime'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/uS9m8OBk3A8wnarts5XeBVwmO4c.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/IXEJQ7znCp7ALzFjJ4Ey24JvUwE.jpg',
    rating: 8.6,
    featured: false,
  },
  {
    title: 'Schindler\'s List',
    description: 'In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.',
    type: 'movie',
    imdbId: 'tt0108052',
    tmdbId: '424',
    year: 1993,
    duration: '3h 15m',
    genre: ['Biography', 'Drama', 'History'],
    category: ['drama'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl7intrGSVQ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/cKJXk2WMeaD9Y4hLJJX4DqVVBQn.jpg',
    rating: 9.0,
    featured: false,
  },
  {
    title: 'Parasite',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    type: 'movie',
    imdbId: 'tt6751668',
    tmdbId: '496243',
    year: 2019,
    duration: '2h 12m',
    genre: ['Drama', 'Thriller'],
    category: ['drama', 'thriller', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/7IeeuqVwTMrVJtFitqpFafSJqKp.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/mnpRdu8vhPjJwvmV74HMwAD9NFb.jpg',
    rating: 8.6,
    featured: true,
  },
  {
    title: 'Joker',
    description: 'In Gotham City, struggling comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
    type: 'movie',
    imdbId: 'tt7366338',
    tmdbId: '475557',
    year: 2019,
    duration: '2h 2m',
    genre: ['Crime', 'Drama', 'Thriller'],
    category: ['drama', 'thriller'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8M2J8WS0IWpxFJa.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/n6bUvigpRFqLou6meyLPDSioGcA.jpg',
    rating: 8.4,
    featured: true,
  },
  {
    title: 'The Avengers',
    description: 'Earth\'s mightiest heroes must come together and learn to fight as a team to protect the world from an alien invasion.',
    type: 'movie',
    imdbId: 'tt0848228',
    tmdbId: '24428',
    year: 2012,
    duration: '2h 23m',
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    category: ['action', 'sci-fi', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/RYMX2tcxCf59rMLQ5GLtsVhLAlj.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/m8wAVJfr8pE5qKnvSVCqb0W5SBn.jpg',
    rating: 8.0,
    featured: false,
  },
  {
    title: 'Avatar',
    description: 'A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.',
    type: 'movie',
    imdbId: 'tt0499549',
    tmdbId: '19995',
    year: 2009,
    duration: '2h 42m',
    genre: ['Action', 'Adventure', 'Fantasy', 'Sci-Fi'],
    category: ['action', 'sci-fi', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/eWGoofwM1r62SJYkNzrHvLFvbkV.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/oe3ZjnP4lVJmMJQQi1fwgj7H8JG.jpg',
    rating: 7.8,
    featured: true,
  },
  {
    title: 'Titanic',
    description: 'A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.',
    type: 'movie',
    imdbId: 'tt0120338',
    tmdbId: '597',
    year: 1997,
    duration: '3h 14m',
    genre: ['Drama', 'Romance'],
    category: ['drama', 'romance'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/9xjZS2rlVxm8SFx8kPC3aIGCOG8.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/pIkWDwIdJFZ0GTR4b2TW0ObYSzE.jpg',
    rating: 7.8,
    featured: false,
  },
  {
    title: 'The Godfather',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.',
    type: 'movie',
    imdbId: 'tt0068646',
    tmdbId: '238',
    year: 1972,
    duration: '2h 55m',
    genre: ['Crime', 'Drama'],
    category: ['drama', 'crime', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1cjexvx.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tmU7GeKVybMWFLad92UUhorWfolcqFn.jpg',
    rating: 9.2,
    featured: true,
  },
  {
    title: 'The Godfather Part II',
    description: 'The continuation of the Godfather story, with alternating scenes showing Vito Corleone\'s rise as a mafia boss and his son Michael\'s expansion of the crime empire.',
    type: 'movie',
    imdbId: 'tt0071562',
    tmdbId: '240',
    year: 1974,
    duration: '3h 20m',
    genre: ['Crime', 'Drama'],
    category: ['drama', 'crime'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/hHdyNJwEBX7Exa6KiNFG2tJoHRA.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fJJNk_E3jC6vbCqcC4ygZo8vDXw.jpg',
    rating: 9.0,
    featured: false,
  },
  {
    title: 'Oppenheimer',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.',
    type: 'movie',
    imdbId: 'tt15398776',
    tmdbId: '940721',
    year: 2023,
    duration: '3h 0m',
    genre: ['Biography', 'Drama', 'History'],
    category: ['drama', 'top-rated', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/8Gxv8kSQNOAbuRrskLMwgtjmnYl.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/fm6KqXpk3M2HVAwT91WCAwcJ7wS.jpg',
    rating: 8.1,
    featured: true,
  },
  // Additional TV Series
  {
    title: 'The Office',
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    type: 'series',
    imdbId: 'tt0386676',
    tmdbId: '2316',
    year: 2005,
    seasons: 9,
    episodes: 201,
    genre: ['Comedy'],
    category: ['comedy', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/wR6MhYL6FHj8KfcUlhSxe67Xqrh.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/3qRfA0qHOHl8fKvHyS9VQxBgZuh.jpg',
    rating: 9.0,
    featured: true,
  },
  {
    title: 'Friends',
    description: 'Follows the personal and professional lives of six twenty- to thirty-something-year-old friends living in Manhattan.',
    type: 'series',
    imdbId: 'tt0108778',
    tmdbId: '1668',
    year: 1994,
    seasons: 10,
    episodes: 236,
    genre: ['Comedy', 'Romance'],
    category: ['comedy', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/aQvJ5WPzZgYVDrxLX4R6W2nRrQD.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/8HdIIL2qtDvasSm0_ZBt03h6XS4.jpg',
    rating: 8.9,
    featured: true,
  },
  {
    title: 'Sherlock',
    description: 'A modern update finds the famous sleuth and his doctor partner solving crime in 21st century London.',
    type: 'series',
    imdbId: 'tt1475582',
    tmdbId: '19885',
    year: 2010,
    seasons: 4,
    episodes: 13,
    genre: ['Crime', 'Drama', 'Mystery'],
    category: ['drama', 'mystery'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/xp6qXyYS9iMfxVfDkCTYoS3V1v0.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/vgMBHpHHZiMwxCCQp1UVR7Gvnfh.jpg',
    rating: 9.1,
    featured: false,
  },
  {
    title: 'The Crown',
    description: 'Follows the political rivalries and romance of Queen Elizabeth II, beginning with her betrothal to Prince Philip in 1947.',
    type: 'series',
    imdbId: 'tt4786824',
    tmdbId: '60573',
    year: 2016,
    seasons: 5,
    episodes: 50,
    genre: ['Biography', 'Drama', 'History'],
    category: ['drama', 'top-rated'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/mUlqnCMm95Eg9tcB4nWY8DLdNu7.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/bQvxMmKvJdnPcESmLOqPQWEE3xJ.jpg',
    rating: 8.6,
    featured: false,
  },
  {
    title: 'The Mandalorian',
    description: 'After the fall of the Empire, a lone bounty hunter operates in the outer reaches of the galaxy, far from the authority of the New Republic.',
    type: 'series',
    imdbId: 'tt8111088',
    tmdbId: '82856',
    year: 2019,
    seasons: 3,
    episodes: 24,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    category: ['action', 'sci-fi', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/eU1i6eHXlzMOlEKleOrvYNr5zn.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/56v2l3MV7ZyWXRsnqcAatin0K23.jpg',
    rating: 8.7,
    featured: true,
  },
  {
    title: 'Westworld',
    description: 'At the intersection of the near future and the reimagined past, waits a world in which every human appetite, no matter how noble or depraved, can be indulged.',
    type: 'series',
    imdbId: 'tt5289236',
    tmdbId: '63247',
    year: 2016,
    seasons: 4,
    episodes: 36,
    genre: ['Drama', 'Mystery', 'Sci-Fi'],
    category: ['sci-fi', 'mystery', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/b0kyC0qMHVweaMtsu0zn9kh9j70.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/a8xZrGM1CKLwC5n0w9MUyXddgSi.jpg',
    rating: 8.5,
    featured: false,
  },
  {
    title: 'Chernobyl',
    description: 'An engineer of Soviet R&D establishment travels back in time from 2006 to 1986 to prevent an explosive secret that a Soviet genie has revealed.',
    type: 'series',
    imdbId: 'tt7366338',
    tmdbId: '86396',
    year: 2019,
    seasons: 1,
    episodes: 5,
    genre: ['Drama', 'History', 'Thriller'],
    category: ['drama', 'history'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/zzP4x4FDss1yO1QPsSkteDFXGj0.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/gEjJVSdMLMNAtWWn86qL2Z6yScD.jpg',
    rating: 9.3,
    featured: false,
  },
  {
    title: 'True Detective',
    description: 'An American anthology police detective series utilizing multiple timelines showing how different environmental pressures influence characters in the same molded lines.',
    type: 'series',
    imdbId: 'tt2356777',
    tmdbId: '60573',
    year: 2014,
    seasons: 4,
    episodes: 30,
    genre: ['Crime', 'Drama', 'Mystery'],
    category: ['crime', 'mystery'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/kLD5xEKqHf5NdTeyqJlWLrKj4b5.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/hyKR6d9VL0MVk2gOVsG7KNO7yqG.jpg',
    rating: 8.9,
    featured: false,
  },
  {
    title: 'House',
    description: 'An anti-social maverick doctor who specializes in diagnostic medicine does whatever it takes to solve puzzling cases that come across his desk.',
    type: 'series',
    imdbId: 'tt0412142',
    tmdbId: '3572',
    year: 2004,
    seasons: 8,
    episodes: 177,
    genre: ['Drama', 'Mystery'],
    category: ['drama', 'mystery'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/3A1yHEOlYVEojD4Df5r4RhXUWUQ.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/sBb6OC9d6n25PvlPX7kn9NQAg0m.jpg',
    rating: 8.8,
    featured: false,
  },
  {
    title: 'The Boys',
    description: 'A group of vigilantes set out to take down corrupt superheroes with no more than smarts and guts.',
    type: 'series',
    imdbId: 'tt1190634',
    tmdbId: '76479',
    year: 2019,
    seasons: 4,
    episodes: 32,
    genre: ['Action', 'Comedy', 'Crime'],
    category: ['action', 'comedy', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/Gw3GZxBkJ2twWn8NFwWvIYeCR7j.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/p0Hw0FPMc5rN5P0agpNJ0w9Lj3R.jpg',
    rating: 8.8,
    featured: true,
  },
  {
    title: 'Narcos',
    description: 'A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug runners who plagued the country and the Americas.',
    type: 'series',
    imdbId: 'tt2707408',
    tmdbId: '45971',
    year: 2015,
    seasons: 3,
    episodes: 30,
    genre: ['Biography', 'Crime', 'Drama'],
    category: ['crime', 'drama', 'trending'],
    thumbnail: 'https://image.tmdb.org/t/p/w500/yZtsmsjiNzAx4R7rVVWAw6Z3RlH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/original/tEjYe5R1jCZGH7Zx5sJNbDZRHYk.jpg',
    rating: 8.9,
    featured: false,
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await User.deleteMany({});
    await Movie.deleteMany({});
    console.log('Cleared existing data');

    // Create admin user
    const hashedPassword = await bcrypt.hash('admin123', 10);
    const admin = await User.create({
      email: 'admin@mindmirror.com',
      password: hashedPassword,
      name: 'Admin',
      role: 'admin',
    });
    console.log('Created admin user:', admin.email);

    // Create sample movies
    const movies = await Movie.insertMany(sampleMovies);
    console.log(`Created ${movies.length} sample movies`);

    console.log('\n✅ Database seeded successfully!');
    console.log('\nAdmin Credentials:');
    console.log('Email: admin@mindmirror.com');
    console.log('Password: admin123');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();
